const octokitPullrequestSuccessfullMock = {
  request: () => ({
    status: 200,
    data: {
      url: 'https://api.github.com/repos/octocat/Hello-World/pulls/1347',
      id: 1,
      node_id: 'MDExOlB1bGxSZXF1ZXN0MQ==',
      html_url: 'https://github.com/octocat/Hello-World/pull/1347',
      diff_url: 'https://github.com/octocat/Hello-World/pull/1347.diff',
      patch_url: 'https://github.com/octocat/Hello-World/pull/1347.patch',
      issue_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347',
      commits_url: 'https://api.github.com/repos/octocat/Hello-World/pulls/1347/commits',
      review_comments_url: 'https://api.github.com/repos/octocat/Hello-World/pulls/1347/comments',
      review_comment_url: 'https://api.github.com/repos/octocat/Hello-World/pulls/comments{/number}',
      comments_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347/comments',
      statuses_url: 'https://api.github.com/repos/octocat/Hello-World/statuses/6dcb09b5b57875f334f61aebed695e2e4193db5e',
      number: 1347,
      state: 'open',
      locked: true,
      title: 'Amazing new feature',
      user: {
        login: 'octocat',
        id: 1,
        node_id: 'MDQ6VXNlcjE=',
        avatar_url: 'https://github.com/images/error/octocat_happy.gif',
        gravatar_id: '',
        url: 'https://api.github.com/users/octocat',
        html_url: 'https://github.com/octocat',
        followers_url: 'https://api.github.com/users/octocat/followers',
        following_url: 'https://api.github.com/users/octocat/following{/other_user}',
        gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
        organizations_url: 'https://api.github.com/users/octocat/orgs',
        repos_url: 'https://api.github.com/users/octocat/repos',
        events_url: 'https://api.github.com/users/octocat/events{/privacy}',
        received_events_url: 'https://api.github.com/users/octocat/received_events',
        type: 'User',
        site_admin: false,
      },
      body: 'Please pull these awesome changes in!',
      labels: [
        {
          id: 208045946,
          node_id: 'MDU6TGFiZWwyMDgwNDU5NDY=',
          url: 'https://api.github.com/repos/octocat/Hello-World/labels/bug',
          name: 'bug',
          description: "Something isn't working",
          color: 'f29513',
          default: true,
        },
      ],
      milestone: {
        url: 'https://api.github.com/repos/octocat/Hello-World/milestones/1',
        html_url: 'https://github.com/octocat/Hello-World/milestones/v1.0',
        labels_url: 'https://api.github.com/repos/octocat/Hello-World/milestones/1/labels',
        id: 1002604,
        node_id: 'MDk6TWlsZXN0b25lMTAwMjYwNA==',
        number: 1,
        state: 'open',
        title: 'v1.0',
        description: 'Tracking milestone for version 1.0',
        creator: {
          login: 'octocat',
          id: 1,
          node_id: 'MDQ6VXNlcjE=',
          avatar_url: 'https://github.com/images/error/octocat_happy.gif',
          gravatar_id: '',
          url: 'https://api.github.com/users/octocat',
          html_url: 'https://github.com/octocat',
          followers_url: 'https://api.github.com/users/octocat/followers',
          following_url: 'https://api.github.com/users/octocat/following{/other_user}',
          gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
          organizations_url: 'https://api.github.com/users/octocat/orgs',
          repos_url: 'https://api.github.com/users/octocat/repos',
          events_url: 'https://api.github.com/users/octocat/events{/privacy}',
          received_events_url: 'https://api.github.com/users/octocat/received_events',
          type: 'User',
          site_admin: false,
        },
        open_issues: 4,
        closed_issues: 8,
        created_at: '2011-04-10T20:09:31Z',
        updated_at: '2014-03-03T18:58:10Z',
        closed_at: '2013-02-12T13:22:01Z',
        due_on: '2012-10-09T23:39:01Z',
      },
      active_lock_reason: 'too heated',
      created_at: '2011-01-26T19:01:12Z',
      updated_at: '2011-01-26T19:01:12Z',
      closed_at: '2011-01-26T19:01:12Z',
      merged_at: '2011-01-26T19:01:12Z',
      merge_commit_sha: 'e5bd3914e2e596debea16f433f57875b5b90bcd6',
      assignee: {
        login: 'octocat',
        id: 1,
        node_id: 'MDQ6VXNlcjE=',
        avatar_url: 'https://github.com/images/error/octocat_happy.gif',
        gravatar_id: '',
        url: 'https://api.github.com/users/octocat',
        html_url: 'https://github.com/octocat',
        followers_url: 'https://api.github.com/users/octocat/followers',
        following_url: 'https://api.github.com/users/octocat/following{/other_user}',
        gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
        organizations_url: 'https://api.github.com/users/octocat/orgs',
        repos_url: 'https://api.github.com/users/octocat/repos',
        events_url: 'https://api.github.com/users/octocat/events{/privacy}',
        received_events_url: 'https://api.github.com/users/octocat/received_events',
        type: 'User',
        site_admin: false,
      },
      assignees: [
        {
          login: 'octocat',
          id: 1,
          node_id: 'MDQ6VXNlcjE=',
          avatar_url: 'https://github.com/images/error/octocat_happy.gif',
          gravatar_id: '',
          url: 'https://api.github.com/users/octocat',
          html_url: 'https://github.com/octocat',
          followers_url: 'https://api.github.com/users/octocat/followers',
          following_url: 'https://api.github.com/users/octocat/following{/other_user}',
          gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
          organizations_url: 'https://api.github.com/users/octocat/orgs',
          repos_url: 'https://api.github.com/users/octocat/repos',
          events_url: 'https://api.github.com/users/octocat/events{/privacy}',
          received_events_url: 'https://api.github.com/users/octocat/received_events',
          type: 'User',
          site_admin: false,
        },
        {
          login: 'hubot',
          id: 1,
          node_id: 'MDQ6VXNlcjE=',
          avatar_url: 'https://github.com/images/error/hubot_happy.gif',
          gravatar_id: '',
          url: 'https://api.github.com/users/hubot',
          html_url: 'https://github.com/hubot',
          followers_url: 'https://api.github.com/users/hubot/followers',
          following_url: 'https://api.github.com/users/hubot/following{/other_user}',
          gists_url: 'https://api.github.com/users/hubot/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/hubot/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/hubot/subscriptions',
          organizations_url: 'https://api.github.com/users/hubot/orgs',
          repos_url: 'https://api.github.com/users/hubot/repos',
          events_url: 'https://api.github.com/users/hubot/events{/privacy}',
          received_events_url: 'https://api.github.com/users/hubot/received_events',
          type: 'User',
          site_admin: true,
        },
      ],
      requested_reviewers: [
        {
          login: 'other_user',
          id: 1,
          node_id: 'MDQ6VXNlcjE=',
          avatar_url: 'https://github.com/images/error/other_user_happy.gif',
          gravatar_id: '',
          url: 'https://api.github.com/users/other_user',
          html_url: 'https://github.com/other_user',
          followers_url: 'https://api.github.com/users/other_user/followers',
          following_url: 'https://api.github.com/users/other_user/following{/other_user}',
          gists_url: 'https://api.github.com/users/other_user/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/other_user/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/other_user/subscriptions',
          organizations_url: 'https://api.github.com/users/other_user/orgs',
          repos_url: 'https://api.github.com/users/other_user/repos',
          events_url: 'https://api.github.com/users/other_user/events{/privacy}',
          received_events_url: 'https://api.github.com/users/other_user/received_events',
          type: 'User',
          site_admin: false,
        },
      ],
      requested_teams: [
        {
          id: 1,
          node_id: 'MDQ6VGVhbTE=',
          url: 'https://api.github.com/teams/1',
          html_url: 'https://github.com/orgs/github/teams/justice-league',
          name: 'Justice League',
          slug: 'justice-league',
          description: 'A great team.',
          privacy: 'closed',
          permission: 'admin',
          members_url: 'https://api.github.com/teams/1/members{/member}',
          repositories_url: 'https://api.github.com/teams/1/repos',
        },
      ],
      head: {
        label: 'octocat:new-topic',
        ref: 'new-topic',
        sha: '6dcb09b5b57875f334f61aebed695e2e4193db5e',
        user: {
          login: 'octocat',
          id: 1,
          node_id: 'MDQ6VXNlcjE=',
          avatar_url: 'https://github.com/images/error/octocat_happy.gif',
          gravatar_id: '',
          url: 'https://api.github.com/users/octocat',
          html_url: 'https://github.com/octocat',
          followers_url: 'https://api.github.com/users/octocat/followers',
          following_url: 'https://api.github.com/users/octocat/following{/other_user}',
          gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
          organizations_url: 'https://api.github.com/users/octocat/orgs',
          repos_url: 'https://api.github.com/users/octocat/repos',
          events_url: 'https://api.github.com/users/octocat/events{/privacy}',
          received_events_url: 'https://api.github.com/users/octocat/received_events',
          type: 'User',
          site_admin: false,
        },
        repo: {
          id: 1296269,
          node_id: 'MDEwOlJlcG9zaXRvcnkxMjk2MjY5',
          name: 'Hello-World',
          full_name: 'octocat/Hello-World',
          owner: {
            login: 'octocat',
            id: 1,
            node_id: 'MDQ6VXNlcjE=',
            avatar_url: 'https://github.com/images/error/octocat_happy.gif',
            gravatar_id: '',
            url: 'https://api.github.com/users/octocat',
            html_url: 'https://github.com/octocat',
            followers_url: 'https://api.github.com/users/octocat/followers',
            following_url: 'https://api.github.com/users/octocat/following{/other_user}',
            gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
            organizations_url: 'https://api.github.com/users/octocat/orgs',
            repos_url: 'https://api.github.com/users/octocat/repos',
            events_url: 'https://api.github.com/users/octocat/events{/privacy}',
            received_events_url: 'https://api.github.com/users/octocat/received_events',
            type: 'User',
            site_admin: false,
          },
          private: false,
          html_url: 'https://github.com/octocat/Hello-World',
          description: 'This your first repo!',
          fork: false,
          url: 'https://api.github.com/repos/octocat/Hello-World',
          archive_url: 'https://api.github.com/repos/octocat/Hello-World/{archive_format}{/ref}',
          assignees_url: 'https://api.github.com/repos/octocat/Hello-World/assignees{/user}',
          blobs_url: 'https://api.github.com/repos/octocat/Hello-World/git/blobs{/sha}',
          branches_url: 'https://api.github.com/repos/octocat/Hello-World/branches{/branch}',
          collaborators_url: 'https://api.github.com/repos/octocat/Hello-World/collaborators{/collaborator}',
          comments_url: 'https://api.github.com/repos/octocat/Hello-World/comments{/number}',
          commits_url: 'https://api.github.com/repos/octocat/Hello-World/commits{/sha}',
          compare_url: 'https://api.github.com/repos/octocat/Hello-World/compare/{base}...{head}',
          contents_url: 'https://api.github.com/repos/octocat/Hello-World/contents/{+path}',
          contributors_url: 'https://api.github.com/repos/octocat/Hello-World/contributors',
          deployments_url: 'https://api.github.com/repos/octocat/Hello-World/deployments',
          downloads_url: 'https://api.github.com/repos/octocat/Hello-World/downloads',
          events_url: 'https://api.github.com/repos/octocat/Hello-World/events',
          forks_url: 'https://api.github.com/repos/octocat/Hello-World/forks',
          git_commits_url: 'https://api.github.com/repos/octocat/Hello-World/git/commits{/sha}',
          git_refs_url: 'https://api.github.com/repos/octocat/Hello-World/git/refs{/sha}',
          git_tags_url: 'https://api.github.com/repos/octocat/Hello-World/git/tags{/sha}',
          git_url: 'git:github.com/octocat/Hello-World.git',
          issue_comment_url: 'https://api.github.com/repos/octocat/Hello-World/issues/comments{/number}',
          issue_events_url: 'https://api.github.com/repos/octocat/Hello-World/issues/events{/number}',
          issues_url: 'https://api.github.com/repos/octocat/Hello-World/issues{/number}',
          keys_url: 'https://api.github.com/repos/octocat/Hello-World/keys{/key_id}',
          labels_url: 'https://api.github.com/repos/octocat/Hello-World/labels{/name}',
          languages_url: 'https://api.github.com/repos/octocat/Hello-World/languages',
          merges_url: 'https://api.github.com/repos/octocat/Hello-World/merges',
          milestones_url: 'https://api.github.com/repos/octocat/Hello-World/milestones{/number}',
          notifications_url: 'https://api.github.com/repos/octocat/Hello-World/notifications{?since,all,participating}',
          pulls_url: 'https://api.github.com/repos/octocat/Hello-World/pulls{/number}',
          releases_url: 'https://api.github.com/repos/octocat/Hello-World/releases{/id}',
          ssh_url: 'git@github.com:octocat/Hello-World.git',
          stargazers_url: 'https://api.github.com/repos/octocat/Hello-World/stargazers',
          statuses_url: 'https://api.github.com/repos/octocat/Hello-World/statuses/{sha}',
          subscribers_url: 'https://api.github.com/repos/octocat/Hello-World/subscribers',
          subscription_url: 'https://api.github.com/repos/octocat/Hello-World/subscription',
          tags_url: 'https://api.github.com/repos/octocat/Hello-World/tags',
          teams_url: 'https://api.github.com/repos/octocat/Hello-World/teams',
          trees_url: 'https://api.github.com/repos/octocat/Hello-World/git/trees{/sha}',
          clone_url: 'https://github.com/octocat/Hello-World.git',
          mirror_url: 'git:git.example.com/octocat/Hello-World',
          hooks_url: 'https://api.github.com/repos/octocat/Hello-World/hooks',
          svn_url: 'https://svn.github.com/octocat/Hello-World',
          homepage: 'https://github.com',
          language: null,
          forks_count: 9,
          stargazers_count: 80,
          watchers_count: 80,
          size: 108,
          default_branch: 'master',
          open_issues_count: 0,
          topics: [
            'octocat',
            'atom',
            'electron',
            'api',
          ],
          has_issues: true,
          has_projects: true,
          has_wiki: true,
          has_pages: false,
          has_downloads: true,
          archived: false,
          disabled: false,
          pushed_at: '2011-01-26T19:06:43Z',
          created_at: '2011-01-26T19:01:12Z',
          updated_at: '2011-01-26T19:14:43Z',
          permissions: {
            admin: false,
            push: false,
            pull: true,
          },
          allow_rebase_merge: true,
          temp_clone_token: 'ABTLWHOULUVAXGTRYU7OC2876QJ2O',
          allow_squash_merge: true,
          allow_merge_commit: true,
          allow_forking: true,
          forks: 123,
          open_issues: 123,
          license: {
            key: 'mit',
            name: 'MIT License',
            url: 'https://api.github.com/licenses/mit',
            spdx_id: 'MIT',
            node_id: 'MDc6TGljZW5zZW1pdA==',
          },
          watchers: 123,
        },
      },
      base: {
        label: 'octocat:master',
        ref: 'master',
        sha: '6dcb09b5b57875f334f61aebed695e2e4193db5e',
        user: {
          login: 'octocat',
          id: 1,
          node_id: 'MDQ6VXNlcjE=',
          avatar_url: 'https://github.com/images/error/octocat_happy.gif',
          gravatar_id: '',
          url: 'https://api.github.com/users/octocat',
          html_url: 'https://github.com/octocat',
          followers_url: 'https://api.github.com/users/octocat/followers',
          following_url: 'https://api.github.com/users/octocat/following{/other_user}',
          gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
          organizations_url: 'https://api.github.com/users/octocat/orgs',
          repos_url: 'https://api.github.com/users/octocat/repos',
          events_url: 'https://api.github.com/users/octocat/events{/privacy}',
          received_events_url: 'https://api.github.com/users/octocat/received_events',
          type: 'User',
          site_admin: false,
        },
        repo: {
          id: 1296269,
          node_id: 'MDEwOlJlcG9zaXRvcnkxMjk2MjY5',
          name: 'Hello-World',
          full_name: 'octocat/Hello-World',
          owner: {
            login: 'octocat',
            id: 1,
            node_id: 'MDQ6VXNlcjE=',
            avatar_url: 'https://github.com/images/error/octocat_happy.gif',
            gravatar_id: '',
            url: 'https://api.github.com/users/octocat',
            html_url: 'https://github.com/octocat',
            followers_url: 'https://api.github.com/users/octocat/followers',
            following_url: 'https://api.github.com/users/octocat/following{/other_user}',
            gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
            organizations_url: 'https://api.github.com/users/octocat/orgs',
            repos_url: 'https://api.github.com/users/octocat/repos',
            events_url: 'https://api.github.com/users/octocat/events{/privacy}',
            received_events_url: 'https://api.github.com/users/octocat/received_events',
            type: 'User',
            site_admin: false,
          },
          private: false,
          html_url: 'https://github.com/octocat/Hello-World',
          description: 'This your first repo!',
          fork: false,
          url: 'https://api.github.com/repos/octocat/Hello-World',
          archive_url: 'https://api.github.com/repos/octocat/Hello-World/{archive_format}{/ref}',
          assignees_url: 'https://api.github.com/repos/octocat/Hello-World/assignees{/user}',
          blobs_url: 'https://api.github.com/repos/octocat/Hello-World/git/blobs{/sha}',
          branches_url: 'https://api.github.com/repos/octocat/Hello-World/branches{/branch}',
          collaborators_url: 'https://api.github.com/repos/octocat/Hello-World/collaborators{/collaborator}',
          comments_url: 'https://api.github.com/repos/octocat/Hello-World/comments{/number}',
          commits_url: 'https://api.github.com/repos/octocat/Hello-World/commits{/sha}',
          compare_url: 'https://api.github.com/repos/octocat/Hello-World/compare/{base}...{head}',
          contents_url: 'https://api.github.com/repos/octocat/Hello-World/contents/{+path}',
          contributors_url: 'https://api.github.com/repos/octocat/Hello-World/contributors',
          deployments_url: 'https://api.github.com/repos/octocat/Hello-World/deployments',
          downloads_url: 'https://api.github.com/repos/octocat/Hello-World/downloads',
          events_url: 'https://api.github.com/repos/octocat/Hello-World/events',
          forks_url: 'https://api.github.com/repos/octocat/Hello-World/forks',
          git_commits_url: 'https://api.github.com/repos/octocat/Hello-World/git/commits{/sha}',
          git_refs_url: 'https://api.github.com/repos/octocat/Hello-World/git/refs{/sha}',
          git_tags_url: 'https://api.github.com/repos/octocat/Hello-World/git/tags{/sha}',
          git_url: 'git:github.com/octocat/Hello-World.git',
          issue_comment_url: 'https://api.github.com/repos/octocat/Hello-World/issues/comments{/number}',
          issue_events_url: 'https://api.github.com/repos/octocat/Hello-World/issues/events{/number}',
          issues_url: 'https://api.github.com/repos/octocat/Hello-World/issues{/number}',
          keys_url: 'https://api.github.com/repos/octocat/Hello-World/keys{/key_id}',
          labels_url: 'https://api.github.com/repos/octocat/Hello-World/labels{/name}',
          languages_url: 'https://api.github.com/repos/octocat/Hello-World/languages',
          merges_url: 'https://api.github.com/repos/octocat/Hello-World/merges',
          milestones_url: 'https://api.github.com/repos/octocat/Hello-World/milestones{/number}',
          notifications_url: 'https://api.github.com/repos/octocat/Hello-World/notifications{?since,all,participating}',
          pulls_url: 'https://api.github.com/repos/octocat/Hello-World/pulls{/number}',
          releases_url: 'https://api.github.com/repos/octocat/Hello-World/releases{/id}',
          ssh_url: 'git@github.com:octocat/Hello-World.git',
          stargazers_url: 'https://api.github.com/repos/octocat/Hello-World/stargazers',
          statuses_url: 'https://api.github.com/repos/octocat/Hello-World/statuses/{sha}',
          subscribers_url: 'https://api.github.com/repos/octocat/Hello-World/subscribers',
          subscription_url: 'https://api.github.com/repos/octocat/Hello-World/subscription',
          tags_url: 'https://api.github.com/repos/octocat/Hello-World/tags',
          teams_url: 'https://api.github.com/repos/octocat/Hello-World/teams',
          trees_url: 'https://api.github.com/repos/octocat/Hello-World/git/trees{/sha}',
          clone_url: 'https://github.com/octocat/Hello-World.git',
          mirror_url: 'git:git.example.com/octocat/Hello-World',
          hooks_url: 'https://api.github.com/repos/octocat/Hello-World/hooks',
          svn_url: 'https://svn.github.com/octocat/Hello-World',
          homepage: 'https://github.com',
          language: null,
          forks_count: 9,
          stargazers_count: 80,
          watchers_count: 80,
          size: 108,
          default_branch: 'master',
          open_issues_count: 0,
          topics: [
            'octocat',
            'atom',
            'electron',
            'api',
          ],
          has_issues: true,
          has_projects: true,
          has_wiki: true,
          has_pages: false,
          has_downloads: true,
          archived: false,
          disabled: false,
          pushed_at: '2011-01-26T19:06:43Z',
          created_at: '2011-01-26T19:01:12Z',
          updated_at: '2011-01-26T19:14:43Z',
          permissions: {
            admin: false,
            push: false,
            pull: true,
          },
          allow_rebase_merge: true,
          temp_clone_token: 'ABTLWHOULUVAXGTRYU7OC2876QJ2O',
          allow_squash_merge: true,
          allow_merge_commit: true,
          forks: 123,
          open_issues: 123,
          license: {
            key: 'mit',
            name: 'MIT License',
            url: 'https://api.github.com/licenses/mit',
            spdx_id: 'MIT',
            node_id: 'MDc6TGljZW5zZW1pdA==',
          },
          watchers: 123,
        },
      },
      _links: {
        self: {
          href: 'https://api.github.com/repos/octocat/Hello-World/pulls/1347',
        },
        html: {
          href: 'https://github.com/octocat/Hello-World/pull/1347',
        },
        issue: {
          href: 'https://api.github.com/repos/octocat/Hello-World/issues/1347',
        },
        comments: {
          href: 'https://api.github.com/repos/octocat/Hello-World/issues/1347/comments',
        },
        review_comments: {
          href: 'https://api.github.com/repos/octocat/Hello-World/pulls/1347/comments',
        },
        review_comment: {
          href: 'https://api.github.com/repos/octocat/Hello-World/pulls/comments{/number}',
        },
        commits: {
          href: 'https://api.github.com/repos/octocat/Hello-World/pulls/1347/commits',
        },
        statuses: {
          href: 'https://api.github.com/repos/octocat/Hello-World/statuses/6dcb09b5b57875f334f61aebed695e2e4193db5e',
        },
      },
      author_association: 'OWNER',
      auto_merge: null,
      draft: false,
      merged: false,
      mergeable: true,
      rebaseable: true,
      mergeable_state: 'clean',
      merged_by: {
        login: 'octocat',
        id: 1,
        node_id: 'MDQ6VXNlcjE=',
        avatar_url: 'https://github.com/images/error/octocat_happy.gif',
        gravatar_id: '',
        url: 'https://api.github.com/users/octocat',
        html_url: 'https://github.com/octocat',
        followers_url: 'https://api.github.com/users/octocat/followers',
        following_url: 'https://api.github.com/users/octocat/following{/other_user}',
        gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
        organizations_url: 'https://api.github.com/users/octocat/orgs',
        repos_url: 'https://api.github.com/users/octocat/repos',
        events_url: 'https://api.github.com/users/octocat/events{/privacy}',
        received_events_url: 'https://api.github.com/users/octocat/received_events',
        type: 'User',
        site_admin: false,
      },
      comments: 10,
      review_comments: 0,
      maintainer_can_modify: true,
      commits: 3,
      additions: 100,
      deletions: 3,
      changed_files: 5,
    },
  }),
};

const octokitCommitsSuccessfullMock = {
  request: () => ({
    status: 200,
    data:
    [
      {
        sha: '8cbd6dbfe02c97107e34b3567a8a35007ac2a449',
        node_id: 'C_kwDOHwJi8toAKDhjYmQ2ZGJmZTAyYzk3MTA3ZTM0YjM1NjdhOGEzNTAwN2FjMmE0NDk',
        commit: {
          author: [Object],
          committer: [Object],
          message: 'feat: prepare env to test',
          tree: [Object],
          url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/git/commits/8cbd6dbfe02c97107e34b3567a8a35007ac2a449',
          comment_count: 0,
          verification: [Object],
        },
        url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/commits/8cbd6dbfe02c97107e34b3567a8a35007ac2a449',
        html_url: 'https://github.com/mauroalderete/action-assign-labels-from-conventionals-commit/commit/8cbd6dbfe02c97107e34b3567a8a35007ac2a449',
        comments_url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/commits/8cbd6dbfe02c97107e34b3567a8a35007ac2a449/comments',
        author: {
          login: 'mauroalderete',
          id: 5913821,
          node_id: 'MDQ6VXNlcjU5MTM4MjE=',
          avatar_url: 'https://avatars.githubusercontent.com/u/5913821?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/mauroalderete',
          html_url: 'https://github.com/mauroalderete',
          followers_url: 'https://api.github.com/users/mauroalderete/followers',
          following_url: 'https://api.github.com/users/mauroalderete/following{/other_user}',
          gists_url: 'https://api.github.com/users/mauroalderete/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/mauroalderete/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/mauroalderete/subscriptions',
          organizations_url: 'https://api.github.com/users/mauroalderete/orgs',
          repos_url: 'https://api.github.com/users/mauroalderete/repos',
          events_url: 'https://api.github.com/users/mauroalderete/events{/privacy}',
          received_events_url: 'https://api.github.com/users/mauroalderete/received_events',
          type: 'User',
          site_admin: false,
        },
        committer: {
          login: 'mauroalderete',
          id: 5913821,
          node_id: 'MDQ6VXNlcjU5MTM4MjE=',
          avatar_url: 'https://avatars.githubusercontent.com/u/5913821?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/mauroalderete',
          html_url: 'https://github.com/mauroalderete',
          followers_url: 'https://api.github.com/users/mauroalderete/followers',
          following_url: 'https://api.github.com/users/mauroalderete/following{/other_user}',
          gists_url: 'https://api.github.com/users/mauroalderete/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/mauroalderete/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/mauroalderete/subscriptions',
          organizations_url: 'https://api.github.com/users/mauroalderete/orgs',
          repos_url: 'https://api.github.com/users/mauroalderete/repos',
          events_url: 'https://api.github.com/users/mauroalderete/events{/privacy}',
          received_events_url: 'https://api.github.com/users/mauroalderete/received_events',
          type: 'User',
          site_admin: false,
        },
        parents: [[Object]],
      },
      {
        sha: '104a4e55ccc01d7f2903a6c90ae2d0fab9b67866',
        node_id: 'C_kwDOHwJi8toAKDEwNGE0ZTU1Y2NjMDFkN2YyOTAzYTZjOTBhZTJkMGZhYjliNjc4NjY',
        commit: {
          author: [Object],
          committer: [Object],
          message: 'build: add gitignore to ignore tmp folder',
          tree: [Object],
          url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/git/commits/104a4e55ccc01d7f2903a6c90ae2d0fab9b67866',
          comment_count: 0,
          verification: [Object],
        },
        url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/commits/104a4e55ccc01d7f2903a6c90ae2d0fab9b67866',
        html_url: 'https://github.com/mauroalderete/action-assign-labels-from-conventionals-commit/commit/104a4e55ccc01d7f2903a6c90ae2d0fab9b67866',
        comments_url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/commits/104a4e55ccc01d7f2903a6c90ae2d0fab9b67866/comments',
        author: {
          login: 'mauroalderete',
          id: 5913821,
          node_id: 'MDQ6VXNlcjU5MTM4MjE=',
          avatar_url: 'https://avatars.githubusercontent.com/u/5913821?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/mauroalderete',
          html_url: 'https://github.com/mauroalderete',
          followers_url: 'https://api.github.com/users/mauroalderete/followers',
          following_url: 'https://api.github.com/users/mauroalderete/following{/other_user}',
          gists_url: 'https://api.github.com/users/mauroalderete/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/mauroalderete/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/mauroalderete/subscriptions',
          organizations_url: 'https://api.github.com/users/mauroalderete/orgs',
          repos_url: 'https://api.github.com/users/mauroalderete/repos',
          events_url: 'https://api.github.com/users/mauroalderete/events{/privacy}',
          received_events_url: 'https://api.github.com/users/mauroalderete/received_events',
          type: 'User',
          site_admin: false,
        },
        committer: {
          login: 'mauroalderete',
          id: 5913821,
          node_id: 'MDQ6VXNlcjU5MTM4MjE=',
          avatar_url: 'https://avatars.githubusercontent.com/u/5913821?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/mauroalderete',
          html_url: 'https://github.com/mauroalderete',
          followers_url: 'https://api.github.com/users/mauroalderete/followers',
          following_url: 'https://api.github.com/users/mauroalderete/following{/other_user}',
          gists_url: 'https://api.github.com/users/mauroalderete/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/mauroalderete/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/mauroalderete/subscriptions',
          organizations_url: 'https://api.github.com/users/mauroalderete/orgs',
          repos_url: 'https://api.github.com/users/mauroalderete/repos',
          events_url: 'https://api.github.com/users/mauroalderete/events{/privacy}',
          received_events_url: 'https://api.github.com/users/mauroalderete/received_events',
          type: 'User',
          site_admin: false,
        },
        parents: [[Object]],
      },
      {
        sha: '488361a5f575431b657348966f6a6861947e1433',
        node_id: 'C_kwDOHwJi8toAKDQ4ODM2MWE1ZjU3NTQzMWI2NTczNDg5NjZmNmE2ODYxOTQ3ZTE0MzM',
        commit: {
          author: [Object],
          committer: [Object],
          message: "Merge branch 'main' into 5-determine-the-labels-to-change-depending-on-the-conventional-commits-that-will-be-merged",
          tree: [Object],
          url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/git/commits/488361a5f575431b657348966f6a6861947e1433',
          comment_count: 0,
          verification: [Object],
        },
        url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/commits/488361a5f575431b657348966f6a6861947e1433',
        html_url: 'https://github.com/mauroalderete/action-assign-labels-from-conventionals-commit/commit/488361a5f575431b657348966f6a6861947e1433',
        comments_url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/commits/488361a5f575431b657348966f6a6861947e1433/comments',
        author: {
          login: 'mauroalderete',
          id: 5913821,
          node_id: 'MDQ6VXNlcjU5MTM4MjE=',
          avatar_url: 'https://avatars.githubusercontent.com/u/5913821?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/mauroalderete',
          html_url: 'https://github.com/mauroalderete',
          followers_url: 'https://api.github.com/users/mauroalderete/followers',
          following_url: 'https://api.github.com/users/mauroalderete/following{/other_user}',
          gists_url: 'https://api.github.com/users/mauroalderete/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/mauroalderete/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/mauroalderete/subscriptions',
          organizations_url: 'https://api.github.com/users/mauroalderete/orgs',
          repos_url: 'https://api.github.com/users/mauroalderete/repos',
          events_url: 'https://api.github.com/users/mauroalderete/events{/privacy}',
          received_events_url: 'https://api.github.com/users/mauroalderete/received_events',
          type: 'User',
          site_admin: false,
        },
        committer: {
          login: 'mauroalderete',
          id: 5913821,
          node_id: 'MDQ6VXNlcjU5MTM4MjE=',
          avatar_url: 'https://avatars.githubusercontent.com/u/5913821?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/mauroalderete',
          html_url: 'https://github.com/mauroalderete',
          followers_url: 'https://api.github.com/users/mauroalderete/followers',
          following_url: 'https://api.github.com/users/mauroalderete/following{/other_user}',
          gists_url: 'https://api.github.com/users/mauroalderete/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/mauroalderete/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/mauroalderete/subscriptions',
          organizations_url: 'https://api.github.com/users/mauroalderete/orgs',
          repos_url: 'https://api.github.com/users/mauroalderete/repos',
          events_url: 'https://api.github.com/users/mauroalderete/events{/privacy}',
          received_events_url: 'https://api.github.com/users/mauroalderete/received_events',
          type: 'User',
          site_admin: false,
        },
        parents: [[Object], [Object]],
      },
      {
        sha: '4ce5ab8ebd9a19c6094ecf408f460657688d06f2',
        node_id: 'C_kwDOHwJi8toAKDRjZTVhYjhlYmQ5YTE5YzYwOTRlY2Y0MDhmNDYwNjU3Njg4ZDA2ZjI',
        commit: {
          author: [Object],
          committer: [Object],
          message: 'feat: get labels before update',
          tree: [Object],
          url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/git/commits/4ce5ab8ebd9a19c6094ecf408f460657688d06f2',
          comment_count: 0,
          verification: [Object],
        },
        url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/commits/4ce5ab8ebd9a19c6094ecf408f460657688d06f2',
        html_url: 'https://github.com/mauroalderete/action-assign-labels-from-conventionals-commit/commit/4ce5ab8ebd9a19c6094ecf408f460657688d06f2',
        comments_url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/commits/4ce5ab8ebd9a19c6094ecf408f460657688d06f2/comments',
        author: {
          login: 'mauroalderete',
          id: 5913821,
          node_id: 'MDQ6VXNlcjU5MTM4MjE=',
          avatar_url: 'https://avatars.githubusercontent.com/u/5913821?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/mauroalderete',
          html_url: 'https://github.com/mauroalderete',
          followers_url: 'https://api.github.com/users/mauroalderete/followers',
          following_url: 'https://api.github.com/users/mauroalderete/following{/other_user}',
          gists_url: 'https://api.github.com/users/mauroalderete/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/mauroalderete/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/mauroalderete/subscriptions',
          organizations_url: 'https://api.github.com/users/mauroalderete/orgs',
          repos_url: 'https://api.github.com/users/mauroalderete/repos',
          events_url: 'https://api.github.com/users/mauroalderete/events{/privacy}',
          received_events_url: 'https://api.github.com/users/mauroalderete/received_events',
          type: 'User',
          site_admin: false,
        },
        committer: {
          login: 'mauroalderete',
          id: 5913821,
          node_id: 'MDQ6VXNlcjU5MTM4MjE=',
          avatar_url: 'https://avatars.githubusercontent.com/u/5913821?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/mauroalderete',
          html_url: 'https://github.com/mauroalderete',
          followers_url: 'https://api.github.com/users/mauroalderete/followers',
          following_url: 'https://api.github.com/users/mauroalderete/following{/other_user}',
          gists_url: 'https://api.github.com/users/mauroalderete/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/mauroalderete/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/mauroalderete/subscriptions',
          organizations_url: 'https://api.github.com/users/mauroalderete/orgs',
          repos_url: 'https://api.github.com/users/mauroalderete/repos',
          events_url: 'https://api.github.com/users/mauroalderete/events{/privacy}',
          received_events_url: 'https://api.github.com/users/mauroalderete/received_events',
          type: 'User',
          site_admin: false,
        },
        parents: [[Object]],
      },
      {
        sha: '37620775fd7ab29168841bcc6c8343e6d7f499e5',
        node_id: 'C_kwDOHwJi8toAKDM3NjIwNzc1ZmQ3YWIyOTE2ODg0MWJjYzZjODM0M2U2ZDdmNDk5ZTU',
        commit: {
          author: [Object],
          committer: [Object],
          message: 'test: context from event path',
          tree: [Object],
          url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/git/commits/37620775fd7ab29168841bcc6c8343e6d7f499e5',
          comment_count: 0,
          verification: [Object],
        },
        url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/commits/37620775fd7ab29168841bcc6c8343e6d7f499e5',
        html_url: 'https://github.com/mauroalderete/action-assign-labels-from-conventionals-commit/commit/37620775fd7ab29168841bcc6c8343e6d7f499e5',
        comments_url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/commits/37620775fd7ab29168841bcc6c8343e6d7f499e5/comments',
        author: {
          login: 'mauroalderete',
          id: 5913821,
          node_id: 'MDQ6VXNlcjU5MTM4MjE=',
          avatar_url: 'https://avatars.githubusercontent.com/u/5913821?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/mauroalderete',
          html_url: 'https://github.com/mauroalderete',
          followers_url: 'https://api.github.com/users/mauroalderete/followers',
          following_url: 'https://api.github.com/users/mauroalderete/following{/other_user}',
          gists_url: 'https://api.github.com/users/mauroalderete/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/mauroalderete/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/mauroalderete/subscriptions',
          organizations_url: 'https://api.github.com/users/mauroalderete/orgs',
          repos_url: 'https://api.github.com/users/mauroalderete/repos',
          events_url: 'https://api.github.com/users/mauroalderete/events{/privacy}',
          received_events_url: 'https://api.github.com/users/mauroalderete/received_events',
          type: 'User',
          site_admin: false,
        },
        committer: {
          login: 'mauroalderete',
          id: 5913821,
          node_id: 'MDQ6VXNlcjU5MTM4MjE=',
          avatar_url: 'https://avatars.githubusercontent.com/u/5913821?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/mauroalderete',
          html_url: 'https://github.com/mauroalderete',
          followers_url: 'https://api.github.com/users/mauroalderete/followers',
          following_url: 'https://api.github.com/users/mauroalderete/following{/other_user}',
          gists_url: 'https://api.github.com/users/mauroalderete/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/mauroalderete/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/mauroalderete/subscriptions',
          organizations_url: 'https://api.github.com/users/mauroalderete/orgs',
          repos_url: 'https://api.github.com/users/mauroalderete/repos',
          events_url: 'https://api.github.com/users/mauroalderete/events{/privacy}',
          received_events_url: 'https://api.github.com/users/mauroalderete/received_events',
          type: 'User',
          site_admin: false,
        },
        parents: [[Object]],
      },
      {
        sha: 'e237fe023a3260ca0ae08190a7dc623c4d6ebb81',
        node_id: 'C_kwDOHwJi8toAKGUyMzdmZTAyM2EzMjYwY2EwYWUwODE5MGE3ZGM2MjNjNGQ2ZWJiODE',
        commit: {
          author: [Object],
          committer: [Object],
          message: 'feat: get pull request info using octokit request',
          tree: [Object],
          url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/git/commits/e237fe023a3260ca0ae08190a7dc623c4d6ebb81',
          comment_count: 0,
          verification: [Object],
        },
        url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/commits/e237fe023a3260ca0ae08190a7dc623c4d6ebb81',
        html_url: 'https://github.com/mauroalderete/action-assign-labels-from-conventionals-commit/commit/e237fe023a3260ca0ae08190a7dc623c4d6ebb81',
        comments_url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/commits/e237fe023a3260ca0ae08190a7dc623c4d6ebb81/comments',
        author: {
          login: 'mauroalderete',
          id: 5913821,
          node_id: 'MDQ6VXNlcjU5MTM4MjE=',
          avatar_url: 'https://avatars.githubusercontent.com/u/5913821?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/mauroalderete',
          html_url: 'https://github.com/mauroalderete',
          followers_url: 'https://api.github.com/users/mauroalderete/followers',
          following_url: 'https://api.github.com/users/mauroalderete/following{/other_user}',
          gists_url: 'https://api.github.com/users/mauroalderete/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/mauroalderete/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/mauroalderete/subscriptions',
          organizations_url: 'https://api.github.com/users/mauroalderete/orgs',
          repos_url: 'https://api.github.com/users/mauroalderete/repos',
          events_url: 'https://api.github.com/users/mauroalderete/events{/privacy}',
          received_events_url: 'https://api.github.com/users/mauroalderete/received_events',
          type: 'User',
          site_admin: false,
        },
        committer: {
          login: 'mauroalderete',
          id: 5913821,
          node_id: 'MDQ6VXNlcjU5MTM4MjE=',
          avatar_url: 'https://avatars.githubusercontent.com/u/5913821?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/mauroalderete',
          html_url: 'https://github.com/mauroalderete',
          followers_url: 'https://api.github.com/users/mauroalderete/followers',
          following_url: 'https://api.github.com/users/mauroalderete/following{/other_user}',
          gists_url: 'https://api.github.com/users/mauroalderete/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/mauroalderete/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/mauroalderete/subscriptions',
          organizations_url: 'https://api.github.com/users/mauroalderete/orgs',
          repos_url: 'https://api.github.com/users/mauroalderete/repos',
          events_url: 'https://api.github.com/users/mauroalderete/events{/privacy}',
          received_events_url: 'https://api.github.com/users/mauroalderete/received_events',
          type: 'User',
          site_admin: false,
        },
        parents: [[Object]],
      },
      {
        sha: '80fb02bc21990a559596c654a7b6a04a452d731a',
        node_id: 'C_kwDOHwJi8toAKDgwZmIwMmJjMjE5OTBhNTU5NTk2YzY1NGE3YjZhMDRhNDUyZDczMWE',
        commit: {
          author: [Object],
          committer: [Object],
          message: 'feat: sketch to get commits',
          tree: [Object],
          url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/git/commits/80fb02bc21990a559596c654a7b6a04a452d731a',
          comment_count: 0,
          verification: [Object],
        },
        url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/commits/80fb02bc21990a559596c654a7b6a04a452d731a',
        html_url: 'https://github.com/mauroalderete/action-assign-labels-from-conventionals-commit/commit/80fb02bc21990a559596c654a7b6a04a452d731a',
        comments_url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/commits/80fb02bc21990a559596c654a7b6a04a452d731a/comments',
        author: {
          login: 'mauroalderete',
          id: 5913821,
          node_id: 'MDQ6VXNlcjU5MTM4MjE=',
          avatar_url: 'https://avatars.githubusercontent.com/u/5913821?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/mauroalderete',
          html_url: 'https://github.com/mauroalderete',
          followers_url: 'https://api.github.com/users/mauroalderete/followers',
          following_url: 'https://api.github.com/users/mauroalderete/following{/other_user}',
          gists_url: 'https://api.github.com/users/mauroalderete/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/mauroalderete/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/mauroalderete/subscriptions',
          organizations_url: 'https://api.github.com/users/mauroalderete/orgs',
          repos_url: 'https://api.github.com/users/mauroalderete/repos',
          events_url: 'https://api.github.com/users/mauroalderete/events{/privacy}',
          received_events_url: 'https://api.github.com/users/mauroalderete/received_events',
          type: 'User',
          site_admin: false,
        },
        committer: {
          login: 'mauroalderete',
          id: 5913821,
          node_id: 'MDQ6VXNlcjU5MTM4MjE=',
          avatar_url: 'https://avatars.githubusercontent.com/u/5913821?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/mauroalderete',
          html_url: 'https://github.com/mauroalderete',
          followers_url: 'https://api.github.com/users/mauroalderete/followers',
          following_url: 'https://api.github.com/users/mauroalderete/following{/other_user}',
          gists_url: 'https://api.github.com/users/mauroalderete/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/mauroalderete/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/mauroalderete/subscriptions',
          organizations_url: 'https://api.github.com/users/mauroalderete/orgs',
          repos_url: 'https://api.github.com/users/mauroalderete/repos',
          events_url: 'https://api.github.com/users/mauroalderete/events{/privacy}',
          received_events_url: 'https://api.github.com/users/mauroalderete/received_events',
          type: 'User',
          site_admin: false,
        },
        parents: [[Object]],
      },
      {
        sha: '3d690ce773ccd1bd1855607a48427ac861a5bf44',
        node_id: 'C_kwDOHwJi8toAKDNkNjkwY2U3NzNjY2QxYmQxODU1NjA3YTQ4NDI3YWM4NjFhNWJmNDQ',
        commit: {
          author: [Object],
          committer: [Object],
          message: 'feat: make service to handle pullrequest request with basic DI to inject any client, add unit test\n'
            + "I don't make an interface to client, but i use the same api designed to octokit.\n"
            + '\n'
            + 'In a future, we could consume some DI library',
          tree: [Object],
          url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/git/commits/3d690ce773ccd1bd1855607a48427ac861a5bf44',
          comment_count: 0,
          verification: [Object],
        },
        url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/commits/3d690ce773ccd1bd1855607a48427ac861a5bf44',
        html_url: 'https://github.com/mauroalderete/action-assign-labels-from-conventionals-commit/commit/3d690ce773ccd1bd1855607a48427ac861a5bf44',
        comments_url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/commits/3d690ce773ccd1bd1855607a48427ac861a5bf44/comments',
        author: {
          login: 'mauroalderete',
          id: 5913821,
          node_id: 'MDQ6VXNlcjU5MTM4MjE=',
          avatar_url: 'https://avatars.githubusercontent.com/u/5913821?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/mauroalderete',
          html_url: 'https://github.com/mauroalderete',
          followers_url: 'https://api.github.com/users/mauroalderete/followers',
          following_url: 'https://api.github.com/users/mauroalderete/following{/other_user}',
          gists_url: 'https://api.github.com/users/mauroalderete/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/mauroalderete/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/mauroalderete/subscriptions',
          organizations_url: 'https://api.github.com/users/mauroalderete/orgs',
          repos_url: 'https://api.github.com/users/mauroalderete/repos',
          events_url: 'https://api.github.com/users/mauroalderete/events{/privacy}',
          received_events_url: 'https://api.github.com/users/mauroalderete/received_events',
          type: 'User',
          site_admin: false,
        },
        committer: {
          login: 'mauroalderete',
          id: 5913821,
          node_id: 'MDQ6VXNlcjU5MTM4MjE=',
          avatar_url: 'https://avatars.githubusercontent.com/u/5913821?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/mauroalderete',
          html_url: 'https://github.com/mauroalderete',
          followers_url: 'https://api.github.com/users/mauroalderete/followers',
          following_url: 'https://api.github.com/users/mauroalderete/following{/other_user}',
          gists_url: 'https://api.github.com/users/mauroalderete/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/mauroalderete/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/mauroalderete/subscriptions',
          organizations_url: 'https://api.github.com/users/mauroalderete/orgs',
          repos_url: 'https://api.github.com/users/mauroalderete/repos',
          events_url: 'https://api.github.com/users/mauroalderete/events{/privacy}',
          received_events_url: 'https://api.github.com/users/mauroalderete/received_events',
          type: 'User',
          site_admin: false,
        },
        parents: [[Object]],
      },
      {
        sha: 'c89c74ba0e0f6585731e2e40bb8cd70f90930a7d',
        node_id: 'C_kwDOHwJi8toAKGM4OWM3NGJhMGUwZjY1ODU3MzFlMmU0MGJiOGNkNzBmOTA5MzBhN2Q',
        commit: {
          author: [Object],
          committer: [Object],
          message: 'build: with pullrequest service',
          tree: [Object],
          url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/git/commits/c89c74ba0e0f6585731e2e40bb8cd70f90930a7d',
          comment_count: 0,
          verification: [Object],
        },
        url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/commits/c89c74ba0e0f6585731e2e40bb8cd70f90930a7d',
        html_url: 'https://github.com/mauroalderete/action-assign-labels-from-conventionals-commit/commit/c89c74ba0e0f6585731e2e40bb8cd70f90930a7d',
        comments_url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/commits/c89c74ba0e0f6585731e2e40bb8cd70f90930a7d/comments',
        author: {
          login: 'mauroalderete',
          id: 5913821,
          node_id: 'MDQ6VXNlcjU5MTM4MjE=',
          avatar_url: 'https://avatars.githubusercontent.com/u/5913821?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/mauroalderete',
          html_url: 'https://github.com/mauroalderete',
          followers_url: 'https://api.github.com/users/mauroalderete/followers',
          following_url: 'https://api.github.com/users/mauroalderete/following{/other_user}',
          gists_url: 'https://api.github.com/users/mauroalderete/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/mauroalderete/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/mauroalderete/subscriptions',
          organizations_url: 'https://api.github.com/users/mauroalderete/orgs',
          repos_url: 'https://api.github.com/users/mauroalderete/repos',
          events_url: 'https://api.github.com/users/mauroalderete/events{/privacy}',
          received_events_url: 'https://api.github.com/users/mauroalderete/received_events',
          type: 'User',
          site_admin: false,
        },
        committer: {
          login: 'mauroalderete',
          id: 5913821,
          node_id: 'MDQ6VXNlcjU5MTM4MjE=',
          avatar_url: 'https://avatars.githubusercontent.com/u/5913821?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/mauroalderete',
          html_url: 'https://github.com/mauroalderete',
          followers_url: 'https://api.github.com/users/mauroalderete/followers',
          following_url: 'https://api.github.com/users/mauroalderete/following{/other_user}',
          gists_url: 'https://api.github.com/users/mauroalderete/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/mauroalderete/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/mauroalderete/subscriptions',
          organizations_url: 'https://api.github.com/users/mauroalderete/orgs',
          repos_url: 'https://api.github.com/users/mauroalderete/repos',
          events_url: 'https://api.github.com/users/mauroalderete/events{/privacy}',
          received_events_url: 'https://api.github.com/users/mauroalderete/received_events',
          type: 'User',
          site_admin: false,
        },
        parents: [[Object]],
      },
      {
        sha: '686b6b0645d31161672be44752404887eae1f382',
        node_id: 'C_kwDOHwJi8toAKDY4NmI2YjA2NDVkMzExNjE2NzJiZTQ0NzUyNDA0ODg3ZWFlMWYzODI',
        commit: {
          author: [Object],
          committer: [Object],
          message: 'fix: name folder mocks',
          tree: [Object],
          url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/git/commits/686b6b0645d31161672be44752404887eae1f382',
          comment_count: 0,
          verification: [Object],
        },
        url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/commits/686b6b0645d31161672be44752404887eae1f382',
        html_url: 'https://github.com/mauroalderete/action-assign-labels-from-conventionals-commit/commit/686b6b0645d31161672be44752404887eae1f382',
        comments_url: 'https://api.github.com/repos/mauroalderete/action-assign-labels-from-conventionals-commit/commits/686b6b0645d31161672be44752404887eae1f382/comments',
        author: {
          login: 'mauroalderete',
          id: 5913821,
          node_id: 'MDQ6VXNlcjU5MTM4MjE=',
          avatar_url: 'https://avatars.githubusercontent.com/u/5913821?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/mauroalderete',
          html_url: 'https://github.com/mauroalderete',
          followers_url: 'https://api.github.com/users/mauroalderete/followers',
          following_url: 'https://api.github.com/users/mauroalderete/following{/other_user}',
          gists_url: 'https://api.github.com/users/mauroalderete/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/mauroalderete/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/mauroalderete/subscriptions',
          organizations_url: 'https://api.github.com/users/mauroalderete/orgs',
          repos_url: 'https://api.github.com/users/mauroalderete/repos',
          events_url: 'https://api.github.com/users/mauroalderete/events{/privacy}',
          received_events_url: 'https://api.github.com/users/mauroalderete/received_events',
          type: 'User',
          site_admin: false,
        },
        committer: {
          login: 'mauroalderete',
          id: 5913821,
          node_id: 'MDQ6VXNlcjU5MTM4MjE=',
          avatar_url: 'https://avatars.githubusercontent.com/u/5913821?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/mauroalderete',
          html_url: 'https://github.com/mauroalderete',
          followers_url: 'https://api.github.com/users/mauroalderete/followers',
          following_url: 'https://api.github.com/users/mauroalderete/following{/other_user}',
          gists_url: 'https://api.github.com/users/mauroalderete/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/mauroalderete/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/mauroalderete/subscriptions',
          organizations_url: 'https://api.github.com/users/mauroalderete/orgs',
          repos_url: 'https://api.github.com/users/mauroalderete/repos',
          events_url: 'https://api.github.com/users/mauroalderete/events{/privacy}',
          received_events_url: 'https://api.github.com/users/mauroalderete/received_events',
          type: 'User',
          site_admin: false,
        },
        parents: [[Object]],
      },
    ],
  }),
};

const octokitCommitsSuccessfullNotConventionalCommitsMock = {
  request: () => ({
    status: 200,
    data:
    [
      {
        commit: {
          message: 'not conventional feat prepare env to test',
        },
      },
      {
        commit: {
          message: 'not conventional build add gitignore to ignore tmp folder',
        },
      },
      {
        commit: {
          message: "Merge branch 'main' into 5-determine-the-labels-to-change-depending-on-the-conventional-commits-that-will-be-merged",
        },
      },
      {
        commit: {
          message: 'not conventional feat get labels before update',
        },
      },
    ],
  }),
};

const octokitSetLabelsSuccessfullMock = {
  request: () => ({
    status: 200,
    data: [
      {
        id: 208045946,
        node_id: 'MDU6TGFiZWwyMDgwNDU5NDY=',
        url: 'https://api.github.com/repos/octocat/Hello-World/labels/bug',
        name: 'bug',
        description: "Something isn't working",
        color: 'f29513',
        default: true,
      },
      {
        id: 208045947,
        node_id: 'MDU6TGFiZWwyMDgwNDU5NDc=',
        url: 'https://api.github.com/repos/octocat/Hello-World/labels/enhancement',
        name: 'enhancement',
        description: 'New feature or request',
        color: 'a2eeef',
        default: false,
      },
    ],
  }),
};

const octokitRequestFailMock = {
  request: () => ({ status: 404, data: {} }),
};

const strategyOctokitSuccessfullMock = {
  request: (url) => {
    switch (url) {
      case 'GET /repos/{owner}/{repository}/pulls/{pullRequestNumber}':
        return octokitPullrequestSuccessfullMock.request();
      case 'GET /repos/{owner}/{repository}/pulls/{pullRequestNumber}/commits':
        return octokitCommitsSuccessfullMock.request();
      case 'PUT /repos/{owner}/{repository}/issues/{pullRequestNumber}/labels':
        return octokitSetLabelsSuccessfullMock.request();
      default:
        return octokitPullrequestSuccessfullMock.request();
    }
  },
};

module.exports = {
  octokitPullrequestSuccessfullMock,
  octokitCommitsSuccessfullMock,
  octokitSetLabelsSuccessfullMock,
  octokitRequestFailMock,
  octokitCommitsSuccessfullNotConventionalCommitsMock,
  strategyOctokitSuccessfullMock,
};
